export default () => ({
  port: parseInt(process.env.PORT, 10) || 3000,
  apiPrefix: process.env.API_PREFIX || 'api/v1',
  nodeEnv: process.env.NODE_ENV || 'development',
  database: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT, 10) || 5432,
    username: process.env.DB_USERNAME || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
    database: process.env.DB_DATABASE || 'logoca',
    synchronize: process.env.DB_SYNCHRONIZE === 'true' || false,
    logging: process.env.DB_LOGGING === 'true' || false,
  },
  jwt: {
    secret: process.env.JWT_SECRET || 'super-secret-jwt-key-change-in-prod',
    expiresIn: process.env.JWT_EXPIRES_IN || '1d',
    refreshSecret: process.env.JWT_REFRESH_SECRET || 'super-secret-refresh-key',
    refreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
  },
  redis: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT, 10) || 6379,
    password: process.env.REDIS_PASSWORD || undefined,
    db: parseInt(process.env.REDIS_DB, 10) || 0,
    ttl: parseInt(process.env.REDIS_TTL, 10) || 3600,
  },
  rabbitmq: {
    url: process.env.RABBITMQ_URL || 'amqp://guest:guest@localhost:5672',
    exchange: process.env.RABBITMQ_EXCHANGE || 'logoca.exchange',
    queueOrders: process.env.RABBITMQ_QUEUE_ORDERS || 'orders.queue',
    queueNotifications: process.env.RABBITMQ_QUEUE_NOTIFICATIONS || 'notifications.queue',
    dlq: process.env.RABBITMQ_DLQ || 'orders.dlq',
  },
  kafka: {
    brokers: (process.env.KAFKA_BROKERS || 'localhost:9092').split(','),
    clientId: process.env.KAFKA_CLIENT_ID || 'logoca-nest',
    groupId: process.env.KAFKA_GROUP_ID || 'logoca-admin-group',
    topicOrders: process.env.KAFKA_TOPIC_ORDERS || 'logoca.orders',
    topicNotifications: process.env.KAFKA_TOPIC_NOTIFICATIONS || 'logoca.notifications',
    topicAdmin: process.env.KAFKA_TOPIC_ADMIN || 'logoca.admin.events',
  },
  ignite: {
    host: process.env.IGNITE_HOST || '127.0.0.1',
    port: parseInt(process.env.IGNITE_PORT, 10) || 10800,
    userCache: process.env.IGNITE_USER_CACHE || 'user-cache',
    adminCache: process.env.IGNITE_ADMIN_CACHE || 'admin-cache',
    user: process.env.IGNITE_USER || undefined,
    password: process.env.IGNITE_PASSWORD || undefined,
  },
  business: {
    markupPercent: parseFloat(process.env.PRODUCT_MARKUP_PERCENT || '20'),
    minOrderQuantity: parseInt(process.env.MIN_ORDER_QUANTITY, 10) || 1,
    freightBasePrice: parseFloat(process.env.FREIGHT_BASE_PRICE || '15.00'),
    freightPerKm: parseFloat(process.env.FREIGHT_PRICE_PER_KM || '1.20'),
    freightPerKg: parseFloat(process.env.FREIGHT_PRICE_PER_KG || '0.80'),
  },
});
